---
title: "Analysis 1"
output: html_document
date: '2022-07-23'
---


```{r Analysis 1}
library(ggplot2)
library(dplyr)
library(scales)
install.packages("viridis")
library(viridis)

#set directory for desktop
# setwd("/Users/apple/Desktop/Project 1/")


#reading in the csvs
test = read.csv("./Data Files/test.csv") #read test.csv
train = read.csv("./Data Files/train.csv") #read train.csv
#GrLivArea: Above grade (ground) living area square feet

train =train %>%filter(Neighborhood == "NAmes" | Neighborhood == "Edwards" | Neighborhood == "BrkSide" )
#updating to per 100 sq feet
train$GrLivArea=train$GrLivArea/100


fit = lm(SalePrice~GrLivArea, data= train)
summary(fit)

#graph with sepearate linear regression lines
bb <- train %>% ggplot(aes(x = GrLivArea, y=SalePrice)) + geom_point(aes(fill=Neighborhood),pch=21,size=3, alpha=.5)+
  xlab("Living area 100 Sq Ft.")+
  ylab("Sales Price")+
  ggtitle("Sales Price vs. Sq. Footage of the Living Area ")+
    scale_y_continuous(label=comma)+
  geom_smooth(method=lm,se=FALSE,fullrange=TRUE,
                  aes(color=Neighborhood))

#plot of linear regression model
bb <- train %>% ggplot(aes(x = GrLivArea, y=SalePrice)) + geom_point(aes(fill=Neighborhood),pch=21,size=3, alpha=.5)+
  xlab("Living area 100 Sq Ft.")+
  ylab("Sales Price")+
  ggtitle("Sales Price vs. Sq. Footage of the Living Area ")+
    scale_y_continuous(label=comma)+
  geom_smooth(method=lm, color="black")
bb  + scale_color_brewer(palette = "BrBG")+ scale_fill_brewer(palette = "BrBG")
```
```{r Analysis 1}

train$res <- resid(fit)

myhist <- hist(train$res, main="Histogram of Residuals", xlab="Residuals", ylim=c(0, 300))
multiplier <- myhist$counts / myhist$density
mydensity <- density(train$res)
mydensity$y <- mydensity$y * multiplier[1]

myx <- seq(min(train$res), max(train$res), length.out= 100)
mymean <- mean(train$res)
mysd <- sd(train$res)

normal <- dnorm(x = myx, mean = mymean, sd = mysd)
lines(myx, normal * multiplier[1], col = "black", lwd = 2)


```
